The-Standard-Organization/ADotNet

ADotNet/Clients/ADotNetClient.cs
ADotNet/Models/Pipelines/AdoPipelines/Exceptions/BuildServiceException.cs
ADotNet/Services/BuildService.Exceptions.cs
ADotNet/Services/BuildService.Validations.cs
ADotNet/Services/BuildService.cs
ADotNet/Services/IBuildService.cs
AdoNet.Tests.Unit/Services/BuildServiceTests.Exceptions.cs
AdoNet.Tests.Unit/Services/BuildServiceTests.Validations.cs
AdoNet.Tests.Unit/Services/BuildServiceTests.cs
AdoNet.Tests.Unit/Services/BuildServiceTests.logic.cs

- Changed AdoService name to BuildService
- Updated `BuildServiceException` message to "Build service exception occured, contact support."

CODE RUB: Change AdoService Name to BuildService

---

.github/workflows/dotnet.yml
ADotNet.Infrastructure.Build/Program.cs

Updated .NET Version - ADotNet

CONFIG : Updated .NET Version - ADotNet

---

ADotNet/ADotNet.csproj
ADotNet/Models/Pipelines/GithubPipelines/DotNets/BuildJob.cs
AdoNet.Tests.Console/Program.cs

DATA: Added Timeout-Minutes

---

ADotNet/ADotNet.csproj
ADotNet/Models/Pipelines/GithubPipelines/DotNets/BuildJob.cs
ADotNet/Models/Pipelines/GithubPipelines/DotNets/Tasks/RunTask.cs
AdoNet.Tests.Console/Program.cs

This PR also includes:
- Allow Windows-Latest version
- Upgrade to version `2.1.0`

DATA: Add `RunTask` and `EnvironmentVariables` Models

---

ADotNet/Models/Pipelines/GithubPipelines/DotNets/PushEvent.cs

DATA: Allow to configure tags on Github PushEvent(s)

---

.github/workflows/dotnet.yml

This PR synchronizes dotnet.yml pipeline with the code defined in `ADotNet.Infrastructure.Build` project.

Synchronize CI pipeline

---

.github/workflows/dotnet.yml
ADotNet.Infrastructure.Build/Program.cs
ADotNet/Models/Pipelines/GithubPipelines/DotNets/EnvironmentVariables.cs
ADotNet/Models/Pipelines/GithubPipelines/DotNets/PushEvent.cs

Closes #58 
This PR makes next changes:
1. Removes:
```diff
- tags:
-  - RELEASE
```
2. Amends:
```diff
- github.ref_name == 'RELEASE'
+ startsWith(github.ref_name, 'RELEASE')
```
3. Updates dotnet version
```diff
- name: Setup .Net
uses: actions/setup-dotnet@v1
with:
-        dotnet-version: 7.0.100-preview.1.22110.4
+        dotnet-version: 7.0.201
-        include-prerelease: true
+        include-prerelease: false
```

CODE RUB: Cleanup add git tag tasks

---

.github/workflows/dotnet.yml
ADotNet/Models/Pipelines/GithubPipelines/DotNets/Tasks/ExtractProjectPropertyTask.cs
AdoNet.Tests.Console/Program.cs

INFRASTRUCTURE: Update ExtractProjectPropertyTask

---

ADotNet/Models/Foundations/Files/Exceptions/FailedFileSerializationException.cs
ADotNet/Models/Foundations/Files/Exceptions/FailedFileServiceException.cs
ADotNet/Models/Foundations/Files/Exceptions/FileDependencyException.cs
ADotNet/Models/Foundations/Files/Exceptions/FileDependencyValidationException.cs
ADotNet/Models/Foundations/Files/Exceptions/FileServiceException.cs
ADotNet/Models/Foundations/Files/Exceptions/FileValidationException.cs
ADotNet/Models/Foundations/Files/Exceptions/InvalidFileContentException.cs
ADotNet/Models/Foundations/Files/Exceptions/InvalidFileDependencyException.cs
ADotNet/Models/Foundations/Files/Exceptions/InvalidFilePathException.cs
ADotNet/Models/Pipelines/AdoPipelines/Exceptions/AdoDependencyException.cs
ADotNet/Models/Pipelines/AdoPipelines/Exceptions/AdoDependencyValidationException.cs
ADotNet/Models/Pipelines/AdoPipelines/Exceptions/AdoValidationException.cs
ADotNet/Models/Pipelines/AdoPipelines/Exceptions/BuildServiceException.cs
ADotNet/Models/Pipelines/AdoPipelines/Exceptions/NullPathException.cs
ADotNet/Models/Pipelines/AdoPipelines/Exceptions/NullPipelineException.cs
AdoNet.Tests.Unit/Services/Builds/BuildServiceTests.Exceptions.cs
AdoNet.Tests.Unit/Services/Builds/BuildServiceTests.Validations.cs
AdoNet.Tests.Unit/Services/Builds/BuildServiceTests.logic.cs
AdoNet.Tests.Unit/Services/Foundations/Files/FileServiceTests.Exceptions.Write.cs
AdoNet.Tests.Unit/Services/Foundations/Files/FileServiceTests.Logic.Write.cs
AdoNet.Tests.Unit/Services/Foundations/Files/FileServiceTests.Validations.Write.cs
README.md

CODE RUB: Standard Version 2.10.0 Upgrade

---

README.md

DOCUMENTATION: Readme Promise Correction

---

ADotNet/Models/Foundations/Files/Exceptions/FailedFileSerializationException.cs
ADotNet/Models/Foundations/Files/Exceptions/FailedFileServiceException.cs
ADotNet/Models/Foundations/Files/Exceptions/FileDependencyException.cs
ADotNet/Models/Foundations/Files/Exceptions/FileDependencyValidationException.cs
ADotNet/Models/Foundations/Files/Exceptions/FileServiceException.cs
ADotNet/Models/Foundations/Files/Exceptions/FileValidationException.cs
ADotNet/Models/Foundations/Files/Exceptions/InvalidFileContentException.cs
ADotNet/Models/Foundations/Files/Exceptions/InvalidFileDependencyException.cs
ADotNet/Models/Foundations/Files/Exceptions/InvalidFilePathException.cs
ADotNet/Models/Pipelines/AdoPipelines/Exceptions/AdoDependencyException.cs
ADotNet/Models/Pipelines/AdoPipelines/Exceptions/AdoDependencyValidationException.cs
ADotNet/Models/Pipelines/AdoPipelines/Exceptions/AdoValidationException.cs
ADotNet/Models/Pipelines/AdoPipelines/Exceptions/BuildServiceException.cs
ADotNet/Models/Pipelines/AdoPipelines/Exceptions/NullPathException.cs
ADotNet/Models/Pipelines/AdoPipelines/Exceptions/NullPipelineException.cs
ADotNet/Services/Builds/BuildService.Exceptions.cs
ADotNet/Services/Builds/BuildService.Validations.cs
ADotNet/Services/Foundations/Files/FileService.Exceptions.cs
ADotNet/Services/Foundations/Files/FileService.Validations.cs
AdoNet.Tests.Unit/Services/Builds/BuildServiceTests.Exceptions.cs
AdoNet.Tests.Unit/Services/Builds/BuildServiceTests.Logic.cs
AdoNet.Tests.Unit/Services/Builds/BuildServiceTests.Validations.cs
AdoNet.Tests.Unit/Services/Builds/BuildServiceTests.cs
AdoNet.Tests.Unit/Services/Foundations/Files/FileServiceTests.Exceptions.Write.cs
AdoNet.Tests.Unit/Services/Foundations/Files/FileServiceTests.Logic.Write.cs
AdoNet.Tests.Unit/Services/Foundations/Files/FileServiceTests.Validations.Write.cs
AdoNet.Tests.Unit/Services/Foundations/Files/FileServiceTests.cs

CODE RUB: Upgrade Test to Standard `2.10.1`

---

README.md

CODE RUB: Update Readme Status Badge to `v2.10.1`

---

.github/workflows/dotnet.yml
ADotNet.Infrastructure.Build/Program.cs
ADotNet/Models/Pipelines/GithubPipelines/DotNets/LabelJob.cs

FOUNDATIONS: Label Job

---

ADotNet/Models/Pipelines/GithubPipelines/DotNets/PublishJobV2.cs

MINOR FOUNDATIONS: Created V2 of PublishJob which will allow you to set the dotnet target version

---

ADotNet/Models/Pipelines/GithubPipelines/DotNets/Job.cs
ADotNet/Models/Pipelines/GithubPipelines/DotNets/LabelJobV2.cs

MINOR FOUNDATIONS: Extended Job base class and created a new version V2 of LabelJob

---

ADotNet/ADotNet.csproj

RELEASES: v3.1.0

---

.github/workflows/build.yml
.github/workflows/prLinter.yml
ADotNet.Infrastructure.Build/ADotNet.Infrastructure.Build.csproj
ADotNet.Infrastructure.Build/Program.cs
ADotNet.Infrastructure.Build/Services/ScriptGenerationService.cs
ADotNet/Models/Pipelines/GithubPipelines/DotNets/RequireIssueOrTaskJob.cs
AdoNet.Tests.Console/ADotNet.Tests.Console.csproj
AdoNet.Tests.Unit/ADotNet.Tests.Unit.csproj

closes #129 
PR Linter / Require Issue Or Task Association  job can be tested by removing and adding the closes statement above.
See #129 for tag association samples

FOUNDATIONS:   Require Issue Or Task

---

README.md

Change NET => BUILD
Closes #123

DOCUMENTATION: Readme Build Badge Fix

---

ADotNet/ADotNet.csproj

This release has two new components: CheckoutTaskV4 and RequireIssueOrTaskJob.
closes #132

RELEASES: v4.0.0

---

README.md

DOCUMENTATION: Fluent API
